export const ServicesData = [
  {
    id: 1,
    pref: "  Ui/Ux",
    icon: "uil uil-web-grid",
    type: "Design",
    title: "Designer",
    one: "User Friendly Interface",
    two: "User Friendly Web applications",
    three: "User Friendly Mobile application ",
    four: "User Friendly Desktop application",
  },
  {
    id: 2,
    icon: "uil uil-arrow",
    pref: "  Frontend",
    type: "Developer",
    title: "Developer",
    one: "User Friendly Interface",
    two: "User Friendly Web applications",
    three: "User Friendly Mobile application ",
    four: "User Friendly Desktop application",
  },
  {
    id: 3,
    icon: "uil uil-pen",
    pref: "  Backend",
    type: "Developer",
    title: "Developer",
    one: "User Friendly Interface",
    two: "User Friendly Web applications",
    three: "User Friendly Mobile application ",
    four: "User Friendly Desktop application",
  },
  {
    id: 4,
    icon: "uil uil-pen",
    pref: "  Desktop",
    type: "Developer",
    title: "Developer",
    one: "User Friendly Interface",
    two: "User Friendly Web applications",
    three: "User Friendly Mobile application ",
    four: "User Friendly Desktop application",
  },
];
